[package]
name = "flamegraph"
version = "0.3.1"
authors = ["Tyler Neely <t@jujit.su>"]
description = "A simple cargo subcommand for generating flamegraphs, using inferno under the hood"
license = "MIT OR Apache-2.0"
repository = "https://github.com/flamegraph-rs/flamegraph"
keywords = ["perf", "flamegraph", "profiling", "cargo", "cargo-subcommand"]
categories = ["command-line-utilities", "development-tools::profiling", "visualization", "development-tools::cargo-plugins"]
readme = "README.md"
edition = "2018"

[[bin]]
name = "cargo-flamegraph"
path = "src/bin/cargo-flamegraph.rs"

[[bin]]
name = "flamegraph"
path = "src/bin/flamegraph.rs"

[dependencies]
inferno = { git = "https://github.com/austinabell/inferno", rev = "d960d573dd78ce28c6c8461dafa04b243fd143d9" }
structopt = "0.3.14"
cargo_metadata = "0.10.0"
opener = "0.4.1"

[target.'cfg(unix)'.dependencies]
signal-hook = "0.1.15"

[profile.release.build-override]
opt-level = 0
